Use pip install instead of git clone to retrieve pyperformance.
redhat-performance/pyperf-wrapper pull request #29
Opened 2024-08-19 21:12 UTC by dvalinrh

2024-08-19 22:06 UTC, kdvalin requested changes

2024-08-19 22:06 UTC, kdvalin commented on pyperf/pyperf_run
> +	echo "--pyperf_version <vers number>: Versionof pyperf to run, default is $PYPERF_VERSION."
```suggestion
	echo "--pyperf_version <vers number>: Version of pyperf to run, default is $PYPERF_VERSION."
```

2024-08-19 22:06 UTC, kdvalin commented on pyperf/pyperf_run
> +PYPERF_VERSION=1.0.4
```suggestion
PYPERF_VERSION="1.0.4"
```

2024-08-19 22:06 UTC, kdvalin commented on pyperf/pyperf_run
> +	python3 -m pip install pyperformance==$PYPERF_VERSION
We should be making sure that `pip` is installed.  Either through `python3 -m ensurepip --upgrade` or by specifying `python3-pip` as a dependency.

2024-08-20 19:45 UTC, kdvalin requested changes
Some things I missed the first round.

@frival Thoughts on this?

2024-08-20 19:45 UTC, kdvalin commented on pyperf/pyperf_run
> +	cd pyperformance
Is this still needed?  Aren't we removing the clone that creates the `pyperformance` dir?

2024-08-20 19:45 UTC, kdvalin commented on pyperf/pyperf_run
> +	echo "--pyperf_version <vers number>: Version of pyperf to run, default is $PYPERF_VERSION."
```suggestion
	echo "--pyperf_version <version number>: Version of pyperf to run, default is $PYPERF_VERSION."
```

2024-08-26 16:07 UTC, kdvalin requested changes

2024-08-26 16:07 UTC, kdvalin commented on pyperf/pyperf_run
> +		exit_out "Failed: python3 -m ensurepip --upgrade" 1
After digging around, RHEL and Ubuntu both use a `python3-pip` package.

Considering [this](https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/9/html/installing_and_using_dynamic_programming_languages/assembly_installing-and-using-python_installing-and-using-dynamic-programming-languages#proc_installing-additional-python-3-packages_assembly_installing-and-using-python) product doc, we should be specifying `python3-pip` as a dependency.

2024-08-26 16:12 UTC, kdvalin requested changes

2024-08-26 16:12 UTC, kdvalin commented on pyperf/pyperf_run
> +PYPERF_VERSION="1.0.4"
Considering future python versions don't work well with this pyperf version, I think we can bump it up to the current latest `1.11.0`.

@frival feel free to object :)

2024-08-30 15:38 UTC, kdvalin approved these changes
LGTM now.  @frival you want to double check I didn't clobber anything accidentally?

2024-08-30 20:02 UTC, frival approved these changes
Aside from the fact that the first commit ought to be split into two, LGTM

2024-09-03 15:36 UTC, merged