Allow pyperf to run more then 1 proc at a time.
redhat-performance/pyperf-wrapper pull request #32
Opened 2024-11-18 20:38 UTC by dvalinrh

Fix it so the pyperf wrapper will run multiple instances of pyperf.  Due to sharing of various files, we have to do this via a venv.

2024-11-19 18:36 UTC, kdvalin requested changes

2024-11-19 18:36 UTC, kdvalin commented on pyperf/run_pyperf
> +python3 -m ensurepip --upgrade
I think we should be installing pip via the python3-pip package

That is the most supported way I see across the distros.  Maybe if the command doesn't exist we run ensurepip.

2024-11-19 18:36 UTC, kdvalin commented on pyperf/run_pyperf
> +pip3_install toml
I think you should be able to condense it into one line, less repetition.

2024-11-19 18:36 UTC, kdvalin commented on pyperf/run_pyperf
> +python3 -m pip install pyperformance==$PYPERF_VERSION
Why is line 17 being repeated here?

2024-12-09 10:25 UTC, dvalinrh commented
Waiting for 
https://github.com/redhat-performance/test_tools-wrappers/pull/48 to be pushed and reviewed.

2025-01-07 19:18 UTC, dvalinrh commented
Determination not to make this change.

2025-01-07 19:18 UTC, closed without merging